### ISSUE TITLE
implement .gro output for other systems than water

### ISSUE THREAD

**Issue by J-Hizzle** [XzzX/mrmd#22]
As of now, .gro files can only be printed correctly for water due to a hardcoded section in lines 51-61 of DumpGRO.cpp setting the atom labels to OW1, HW2, HW3, rather than the actual names of the atoms. This should be changed to read the names from the Atoms struct and print them to the file accordingly.

**Comment by XzzX** [comment]
The `Atoms` struct does not store a name. It only stores a `type` we can use this to convert to a string. Depending on what you want to do with it you could also use the H5MD output that already outputs the `type` and you can use it in postprocessing.

Regarding GRO output. Would it be sufficient to change the API to also take a `std::vector<std::string>>` for the `type` to `name` conversion?

**Comment by J-Hizzle** [comment]
A change of API would be convenient, yes. One could also add an option for the residue names that are at the moment hardcoded in lines 71 and 83 of DumpGRO.cpp.
