### ISSUE TITLE
Standardize H5MD Output

### ISSUE THREAD

**Issue by J-Hizzle** [XzzX/mrmd#27]
Currently, the H5MD output of MRMD does not meet some of the requirements of the H5MD standard (see ref. [1]) This creates problems when reading the output with analysis packages such as MDAnalysis, which could otherwise be a very convenient interface. Consequently, meeting the requirements should be accomplished. 

[1] P. de Buyl, P. H. Colberg, and F. Höfling, [H5MD: a structured, efficient, and portable file format for molecular data](http://dx.doi.org/10.1016/j.cpc.2014.01.018), Comput. Phys. Commun. 185, 1546 (2014) [[arXiv:1308.6382]](http://arxiv.org/abs/1308.6382).

**Comment by XzzX** [comment]
Can you be more explicit about what is missing/wrong?

**Comment by J-Hizzle** [comment]
> Can you be more explicit about what is missing/wrong?

Ah, yes. I've found three changes that would need to be made:

1. In section 3.7 in ref. [1] (see above), they define the name of the `position` `item` to be "position" rather than "pos", as it is in MRMD at the moment. This leads to MDAnalysis not recognizing at all that there even are positions stored in the file. 
2. Same section, same problem, but with the `velocity` `item`.
3. `edges` is at the moment stored as an `attribute`, but it is supposed to be `data` according to section 3.8 in the case of an NVT simulation. For NPT, one would need to store it as an`item` with `step`, `time` and `value` attached as `data`. This leads to MDAnalysis not recognizing the box edges at all, which lets the RDF function crash.

**Comment by XzzX** [comment]
Interesting. I thought I used MDAnalysis in the past with this output. But you are right. Can you check if #28 is conformant to the standard?

1 and 2 are no problem. However, 3 has some caveats. Does the standard assume the box is located at (0,0,0)? This does not have to be the case for MRMD. So we might need to shift all positions.

Previously I was also using the format for checkpoint and restart my simulation. However the format is not sufficient reconstruct the whole simulation. This is why I additionally need `minCorner`, `maxCorner`, and `ghostLayerThickness`.

**Comment by J-Hizzle** [comment]
Please ignore these pushes on my fork above. This was the changes I attempted earlier. But now I'm checking your pull request #28, so let's stick to that.

**Comment by XzzX** [comment]
> Please ignore these pushes on my fork above. This was the changes I attempted earlier. But now I'm checking your pull request #28, so let's stick to that.

Oh, you did not link your attemp. I am sorry I was not aware of your attempt, I did not want to silently dismiss your work. Please make sure to reference your work as soon as your start somewhere, so I get notified about it. You can even create a draft PR.

**Comment by J-Hizzle** [comment]
No problem! It was all local until today. Next time I will use a draft PR as you suggest.
